/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rodzmell.menu.views;

import com.rodzmell.menu.controller.MenuController;
import com.rodzmell.menu.misc.ConfigPropiedades;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ELECTRONICA8901
 */
public class MenuOpciones extends javax.swing.JFrame {

    MenuController mc;
    ConfigPropiedades cp;
    Settings settings;

    /**
     * Creates new form MenuOpciones
     */
    public MenuOpciones() {
        initComponents();
        setUpController();
        aplySettings();
    }

    public void setUpController() {
        mc = new MenuController(this);
        btnNuevo.addActionListener(mc);
        btnCerrar.addActionListener(mc);
    }

    public void aplySettings() {
        ConfigPropiedades cp = new ConfigPropiedades();
        cp.open();
        if (cp.isFileExists()) {
            this.jLabel1.setText(cp.getProperty("Empresa"));
            this.jLabel2.setText(cp.getProperty("Direccion"));
            this.jLabel3.setText(cp.getProperty("Numero"));
        } else {
            JOptionPane.showInternalMessageDialog(null, "¡Importante! \nEs necesario realizar la configuración \nSolo se realizará una vez", "Configuración", JOptionPane.ERROR_MESSAGE);
            mc.showSetting();
            cp.open();
            this.jLabel1.setText(cp.getProperty("Empresa"));
            this.jLabel2.setText(cp.getProperty("Direccion"));
            this.jLabel3.setText(cp.getProperty("Numero"));
        }
    }

    public void isVisible(JInternalFrame NominaFrame, boolean maxizeFrame) {
        jDesktopPane2.add(NominaFrame);
        NominaFrame.setVisible(true);
        if (maxizeFrame) {
            jDesktopPane2.getDesktopManager().maximizeFrame(NominaFrame);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Nomina");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrar.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/padlock.png"))); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.setActionCommand("CerrarA");
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 160, 60));
        btnCerrar.getAccessibleContext().setAccessibleName("");
        btnCerrar.setOpaque(false);
        btnCerrar.setContentAreaFilled(false); //to make the content area transparent
        btnCerrar.setBorderPainted(false); //to make the borders transparent

        btnNuevo.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/folder.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setActionCommand("NuevoA");
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 160, 60));
        btnNuevo.getAccessibleContext().setAccessibleName("");
        btnNuevo.setOpaque(false);
        btnNuevo.setContentAreaFilled(false); //to make the content area transparent
        btnNuevo.setBorderPainted(false); //to make the borders transparent

        jDesktopPane2.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );

        jPanel1.add(jDesktopPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1200, 438));

        jLabel1.setFont(new java.awt.Font("SimSun", 1, 16)); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, 20));

        jLabel2.setFont(new java.awt.Font("SimSun", 1, 16)); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, -1, 20));

        jLabel3.setFont(new java.awt.Font("SimSun", 1, 16)); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, -1, 20));

        fondo.setFont(new java.awt.Font("SimSun", 1, 16)); // NOI18N
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/WhatsApp Image 2022-02-20 at 11.40.26 PM.jpeg"))); // NOI18N
        fondo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel fondo;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
