/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

package com.rodzmell.menu.views;

import com.rodzmell.menu.controller.NominaController;
import com.rodzmell.menu.models.ArregloNomina;
import com.rodzmell.menu.models.NominaData;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class NominaFrame extends javax.swing.JInternalFrame {

    /** Creates new form NominaFrame */
    public NominaFrame() {
        initComponents();
        modelo = (DefaultTableModel) NominaTable.getModel();
        inicio();
        
    }
   public DefaultTableModel modelo;
    ArregloNomina nomina = new ArregloNomina();
        
    
    public void agregarEmpleado(){
        try{
       String name = t1.getText();
       double sala = Double.parseDouble(t2.getText());
       int extraTime = Integer.parseInt(t3.getText());
       int day = Integer.parseInt(t4.getText());
       double zona = Double.parseDouble(t6.getText());
       int year = Integer.parseInt(t5.getText());
       double comisi = Double.parseDouble(t7.getText());
       NominaData data = new NominaData(name, sala, extraTime, day, zona, comisi, year);
       nomina.adicionar(data);
       modelo.setRowCount(0);
       for(int i=0; i<nomina.tamaño(); i++){
           Object []info = {nomina.obtener(i).getNombre(), nomina.obtener(i).getSalario(),nomina.obtener(i).getHorasExtras(), nomina.obtener(i).getIngresosPorHorasExtras(), nomina.obtener(i).getDias(), nomina.obtener(i).getIngresosPorVacaciones()
           ,nomina.obtener(i).getAñosLaborados(), nomina.obtener(i).getIngresosPorAntiguedad(), nomina.obtener(i).getZonaje(), nomina.obtener(i).getComisiones(), nomina.obtener(i).getRemuneracionBruta()
           , nomina.obtener(i).getInss(), nomina.obtener(i).getIr(), nomina.obtener(i).getTotalDeducciones(), nomina.obtener(i).getRemuneracionNeta()
           , nomina.obtener(i).getInssPatronal(), nomina.obtener(i).getInatec(), nomina.obtener(i).getTotalImpuestos()
           , nomina.obtener(i).getAguinaldo(), nomina.obtener(i).getTotalAPagar()};
           modelo.addRow(info);
           
           t1.setText("");
           t2.setText("");
           t3.setText("");
           t4.setText("");
           t5.setText("");
           t6.setText("");
           t7.setText("");
           
           System.out.print(nomina.tamaño());
       }
    }catch(Exception e){
    JOptionPane.showMessageDialog(null, "Verifique los datos ingresados por favor", "Advertencia", HEIGHT);
}
    }
    
    
     public ArregloNomina guardado(){
         System.out.println(nomina.tamaño());
         return nomina;
     }
    
        public void inicio(){
         NominaController nc = new NominaController(this);
         addButton.addActionListener(nc);
         saveButton.addActionListener(nc);
         readButton.addActionListener(nc);
        
     }
     
        public void lectura(){
         NominaController cn = new NominaController(this);
         
         nomina = cn.Leer();
         modelo.setRowCount(0);
         
         for(int i=0; i<nomina.tamaño(); i++){
           Object []info = {nomina.obtener(i).getNombre(), nomina.obtener(i).getSalario(),nomina.obtener(i).getHorasExtras(), nomina.obtener(i).getIngresosPorHorasExtras(), nomina.obtener(i).getDias(), nomina.obtener(i).getIngresosPorVacaciones()
           ,nomina.obtener(i).getAñosLaborados(), nomina.obtener(i).getIngresosPorAntiguedad(), nomina.obtener(i).getZonaje(), nomina.obtener(i).getComisiones(), nomina.obtener(i).getRemuneracionBruta()
           , nomina.obtener(i).getInss(), nomina.obtener(i).getIr(), nomina.obtener(i).getTotalDeducciones(), nomina.obtener(i).getRemuneracionNeta()
           , nomina.obtener(i).getInssPatronal(), nomina.obtener(i).getInatec(), nomina.obtener(i).getTotalImpuestos()
           , nomina.obtener(i).getAguinaldo(), nomina.obtener(i).getTotalAPagar()};
           modelo.addRow(info);
           
           
       
         }
         System.out. print(nomina.tamaño());
     }
             
      
        
        
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreyapellidos = new javax.swing.JLabel();
        salariobasico = new javax.swing.JLabel();
        horasextras = new javax.swing.JLabel();
        anioslaborados = new javax.swing.JLabel();
        diasvacionesacumuladas = new javax.swing.JLabel();
        zonaje = new javax.swing.JLabel();
        comisiones = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        NominaTable = new javax.swing.JTable();
        t7 = new javax.swing.JTextField();
        readButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Nomina");
        setAutoscrolls(true);

        nombreyapellidos.setText("Nombre y Apellidos");

        salariobasico.setText("Salario básico");

        horasextras.setText("Horas Extras");

        anioslaborados.setText("Años Laborados");

        diasvacionesacumuladas.setText("Dias de vacaciones acumulados");

        zonaje.setText("Zonaje");

        comisiones.setText("Comisiones");

        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/49576_new_add_plus_user_icon (1).png"))); // NOI18N
        addButton.setText("Agregar");
        addButton.setActionCommand("add");

        jScrollPane2.setBackground(new java.awt.Color(153, 204, 255));

        NominaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Y apellidos", "Salario básico", "Horas Extras ", "Inresos por horas extras", "Dias", "Ingresos por vacaciones", "Años laborados", "Ingresos por antiguedad", "Zonaje", "Comisiones", "Remuneración Bruta", "INSS laboral", "IR", "Total deducciones", "Remuneración neta", "INSS patronal", "INATEC", "Total impuestos", "Aguinaldo", "Total a Pagar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        NominaTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(NominaTable);

        readButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Files-icon.png"))); // NOI18N
        readButton.setText("Mostrar");
        readButton.setActionCommand("read");

        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/85542_guardar_save_icon (3).png"))); // NOI18N
        saveButton.setText("Guardar");
        saveButton.setActionCommand("save");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(salariobasico)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(nombreyapellidos)
                                    .addGap(94, 94, 94)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(horasextras)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(diasvacionesacumuladas))
                        .addGap(177, 177, 177)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(anioslaborados)
                            .addComponent(zonaje)
                            .addComponent(comisiones))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(t6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(t5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t7, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(saveButton, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(readButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addComponent(nombreyapellidos))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(anioslaborados))))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zonaje)
                            .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(salariobasico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(addButton)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(horasextras)
                            .addComponent(saveButton))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diasvacionesacumuladas)
                    .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comisiones))
                .addGap(1, 1, 1)
                .addComponent(readButton)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


   
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable NominaTable;
    public javax.swing.JButton addButton;
    private javax.swing.JLabel anioslaborados;
    private javax.swing.JLabel comisiones;
    private javax.swing.JLabel diasvacionesacumuladas;
    private javax.swing.JLabel horasextras;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nombreyapellidos;
    public javax.swing.JButton readButton;
    private javax.swing.JLabel salariobasico;
    public javax.swing.JButton saveButton;
    public javax.swing.JTextField t1;
    public javax.swing.JTextField t2;
    public javax.swing.JTextField t3;
    public javax.swing.JTextField t4;
    public javax.swing.JTextField t5;
    public javax.swing.JTextField t6;
    public javax.swing.JTextField t7;
    private javax.swing.JLabel zonaje;
    // End of variables declaration//GEN-END:variables

}
